'use client'
import {Metadata} from "next";
import Posts from "@/components/Posts";


async function getData() {
    try {
        const response = await fetch('https://jsonplaceholder.typicode.com/posts')
        return response.json()
    } catch (err) {
        console.log(err.message)
    }

}

export const metadata: Metadata = {
    title: 'Blog | Next App',
    description: 'Generated by create next app',
}

export default async function Blog() {
    const posts = await getData()

    return (
        <>
            <h1> Blog Page </h1>
            <Posts posts={posts}/>
        </>
    )
};

