import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import TheHeader from "@/components/TheHeader";
import styles from './page.module.css'
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <TheHeader/>
        <div className={styles.container}>
            {children}
        </div>
        </body>
        </html>
    )
}
